# Generated by Django 5.1.7 on 2025-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='name',
            new_name='bookmark_name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='card_name',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='name',
            new_name='folder_name',
        ),
    ]
