# Generated by Django 5.1.7 on 2025-03-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_bookmark_bookmark_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='status',
            field=models.CharField(choices=[('card', 'Asignado a una tarjeta'), ('folder', 'Dentro de un folder'), ('unassigned', 'Sin asignación')], default='unassigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.card'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.card'),
        ),
    ]
